MVC_loginIdentityCore5/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_loginIdentityCore5.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MVC_loginIdentityCore5/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_loginIdentityCore5.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

MVC_loginIdentityCore5/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MVC_loginIdentityCore5.ViewModel;
using System.Threading.Tasks;

namespace MVC_loginIdentityCore5.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public Login model { get; set; }
        public LoginModel( SignInManager<IdentityUser> signInManager)
        {

            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync ( string returnurl =null )
        {
            if (ModelState.IsValid)
            {
                var IdentityResult = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
                if (IdentityResult.Succeeded)
                {
                    if (returnurl == null | returnurl == "/")
                    {
                        return RedirectToPage("Index");

                    }
                    else
                    {
                        return RedirectToPage(returnurl);

                    }
                }


            }


            return Page();
        }

    }
}

MVC_loginIdentityCore5/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MVC_loginIdentityCore5.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public  IActionResult OnPostDontLogout()
        {

            return RedirectToPage("Index");
        }

    }
}

MVC_loginIdentityCore5/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MVC_loginIdentityCore5.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MVC_loginIdentityCore5/Pages/Register.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_loginIdentityCore5.ViewModel;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;

namespace MVC_loginIdentityCore5.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        [BindProperty]
        public Register model { get; set; }

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<ActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = model.Email,
                    Email = model.Email

                };
                var result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");

                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }


            }

            return Page();

        }
    }
}

MVC_loginIdentityCore5/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_loginIdentityCore5/Pages/Login.cshtml
@page
@model MVC_loginIdentityCore5.Pages.LoginModel
@{
}

<div class="container" mt-5>
    <div  class="row justify-content-center align-items-center"  >
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
            <form method="post">
                <div class="Mb-3">
                    <label class="form-Label" asp-for="model.Email"> Email Address</label>
                    <input type="text" asp-for="model.Email" class="form-control" />
                    <span asp-validation-for="model.Email" class="text-danger"></span>
                </div>
                <div class="Mb-3">
                    <label class="form-Label" asp-for="model.Password"> Password</label>
                    <input type="password" asp-for="model.Password" class="form-control" />
                    <span asp-validation-for="model.Password" class="text-danger"></span>
                </div>
                <div class="Mb-3 form-check">

                    <input type="checkbox" asp-for="model.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="model.RememberMe"> RememberMe?</label>
                </div>
                <div mb-3>
                    <button type="submit"  class="btn btn-primary"> Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

MVC_loginIdentityCore5/Pages/Logout.cshtml
@page
@model MVC_loginIdentityCore5.Pages.LogoutModel
@{
}

<form  method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p> Are you sure you want to logout? </p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout"> Yes</button>
                    <button class="btn btn-light ml-5 border-dark"  asp-page-handler="DontLogout"> No</button>
                </p>

            </div>

        </div>
    </div>

</form>

MVC_loginIdentityCore5/Pages/Register.cshtml
@page
@model MVC_loginIdentityCore5.Pages.RegisterModel
@{
}
<div class="container mt-5">
    <div class="row justify-content-center align-items-center" >
        <div class="col-sm-12 col-md-12 col-lg-4" >
            <h1 class="mb-3" >Register </h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="col-form-label" asp-for="model.Email">Email Address </label>
                    <input type="text" asp-for="model.Email" class="form-control" />
                    <span asp-validation-for="model.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="col-form-label" asp-for="model.Password">Password </label>
                    <input type="password" asp-for="model.Password" class="form-control" />
                    <span asp-validation-for="model.Password" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="col-form-label" asp-for="model.ConfirmPassword">Confirm Password</label>
                    <input type="password" asp-for="model.ConfirmPassword" class="form-control" />
                    <span asp-validation-for="model.ConfirmPassword" class="text-danger"></span>
                </div>

                <div>
                    <button type="submit" class="btn btn-primary"> Register</button>
                </div>

            </form>
        </div>
    </div>
</div>

MVC_loginIdentityCore5/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_loginIdentityCore5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MVC_loginIdentityCore5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar nav d-flex justify-content-end" >
                        <li class="nav-item ">
                            <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                        </li>

                    </ul>

                    }
                    else
                    {
                <ul class="navbar nav d-flex justify-content-end flex-grow-1">
                    <li class="nav-item">
                        <a class="btn btn-primary"  asp-page="/Login">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="btn"  asp-page="/Register">Register</a>
                    </li>

                </ul>

                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_loginIdentityCore5 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>